config/routes.rb
Rails.application.routes.draw do
  root 'kpts#index'
  resources :kpts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/common_kpt_item_validator.rb
module CommonKptItemValidator
  extend ActiveSupport::Concern
  included do
    validates :title, presence: true
  end
end

app/models/keep_item.rb
class KeepItem < ApplicationRecord
  belongs_to :kpt
  include CommonKptItemValidator
end

app/models/kpt.rb
class Kpt < ActiveRecord::Base
  with_options inverse_of: :kpt do |assoc|
    assoc.has_many :keep_items
    assoc.has_many :problem_items
    assoc.has_many :try_items
  end

  validates :title, presence: true

  accepts_nested_attributes_for :keep_items, allow_destroy: true
  accepts_nested_attributes_for :problem_items, allow_destroy: true
  accepts_nested_attributes_for :try_items, allow_destroy: true
end

app/models/problem_item.rb
class ProblemItem < ApplicationRecord
  belongs_to :kpt
  include CommonKptItemValidator
end

app/models/try_item.rb
class TryItem < ApplicationRecord
  belongs_to :kpt
  include CommonKptItemValidator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kpts_controller.rb
class KptsController < ApplicationController
  def index
    @kpts = Kpt.all
  end

  def show
    @kpt = Kpt.find(params[:id])
  end

  def new
    @kpt = Kpt.new
    build_kpt_items
  end

  def create
    @kpt = Kpt.new(kpt_params)
    if @kpt.save
      redirect_to kpts_path, notice: "Success to create new KPT project"
    else
      flash[:alert] = "Failed to create new KPT project"
      render :new
    end
  end

  def edit
    @kpt = Kpt.find(params[:id])
  end

  def update
    @kpt = Kpt.find(params[:id])
    if @kpt.update(kpt_params)
      redirect_to kpts_path, notice: "Success to update KPT project"
    else
      flash[:alert] = "Failed to update KPT project"
      render :new
    end
  end

  def destroy
    kpt = Kpt.find(params[:id])
    if kpt.destroy
      redirect_to kpts_path, notice: "Success delete KPT Project"
    else
      flash[:alert] = "Failed to delete KPT project"
      render :index
    end
  end

  private
  def kpt_params
    params.require(:kpt).permit(
      :title,
      keep_items_attributes: [:id, :title, :description, :_destroy],
      problem_items_attributes: [:id, :title, :description, :_destroy],
      try_items_attributes: [:id, :title, :description, :checked, :_destroy]
    )
  end

  def build_kpt_items
    @kpt.keep_items.build
    @kpt.problem_items.build
    @kpt.try_items.build
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kpts/_keep_item_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :title,"タイトル" %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :title,"詳細" %>
    <%= f.text_field :description %>
  </div>
  <%= link_to_remove_association 'remove keep', f %>
</div>

app/views/kpts/_problem_item_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :title,"タイトル" %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :title,"詳細" %>
    <%= f.text_field :description %>
  </div>
  <%= link_to_remove_association 'remove problem', f %>
</div>

app/views/kpts/_try_item_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :title,"タイトル" %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :title,"詳細" %>
    <%= f.text_field :description %>
  </div>
  <%= link_to_remove_association 'remove try', f %>
</div>

app/views/kpts/edit.html.erb
<h1>KPT edit</h1>

<%= form_for(@kpt) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit "Update" %>
<% end %>

app/views/kpts/index.html.erb
<h1>KPT index</h1>

<ul>
  <%= render "layouts/flash_error", object: @kpts %>
  <% @kpts.each do |kpt| %>
    <li>
      <%= kpt.title %>
      <%= link_to "Show", kpt_path(kpt.id) %>
      <%= link_to "Edit", edit_kpt_path(kpt.id) %>
    </li>
  <% end %>
</ul>

<p><%= link_to "Top", kpts_path %></p>
<p><%= link_to "New KPT Project", new_kpt_path %></p>

app/views/kpts/new.html.erb
<h1>KPT new</h1>
<%= render "layouts/flash_error", object: @kpts %>

<%= form_for @kpt do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <br>
  <br>
  <div id="keep_items">
    <%= f.label :keep_items, "Keep" %>
    <%= f.fields_for :keep_items do |keep_item_form| %>
      <%= render 'keep_item_fields', f: keep_item_form %>
      <div class="links">
        <%= link_to_add_association 'add keep', f, :keep_items %>
      </div>
    <% end %>
  </div>

  <br>
  <div id="problem_items">
    <%= f.label :problem_items, "Problem" %>
    <%= f.fields_for :problem_items do |problem_item_form| %>
      <%= render 'problem_item_fields', f: problem_item_form %>
      <div class="links">
        <%= link_to_add_association 'add problem', f, :problem_items %>
      </div>
    <% end %>
  </div>

  <br>
  <div id="try_items">
    <%= f.label :try_items, "Try" %>
    <%= f.fields_for :try_items do |try_item_form| %>
      <%= render 'try_item_fields', f: try_item_form %>
      <div class="links">
        <%= link_to_add_association 'add try', f, :try_items %>
      </div>
    <% end %>
  </div>

  <%= f.submit "Create" %>
<% end %>

app/views/kpts/show.html.erb
<h1><%= @kpt.title %></h1>

<p>Keep</p>
<ul>
  <% @kpt.keep_items.each do |keep| %>
    <li>
      <%= keep.title %>
      <small><%= keep.description %></small>
    </li>
  <% end %>
</ul>

<p>Problem</p>
<ul>
  <% @kpt.problem_items.each do |problem| %>
    <li>
      <%= problem.title %>
      <small><%= problem.description %></small>
    </li>
  <% end %>
</ul>

<p>Try</p>
<ul>
  <% @kpt.try_items.each do |try| %>
    <li>
      <%= try.title %>
      <small><%= try.description %></small>
    </li>
  <% end %>
</ul>

<%= link_to "Delete this KPT project", kpt_path(@kpt.id), method: :delete, data: { confirm: "Are you sure you want to delete this?" } %>

app/views/layouts/_flash_error.html.erb
<% if flash[:alert] %>
  <p><%= flash[:alert] %></p>
<% elsif flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Klain</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>